apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-pj
  labels:
    app: capstone-pj
  namespace: default
spec:
  replicas: 3
  progressDeadlineSeconds: 3600
  selector:
    matchLabels:
      app: capstone-pj
  template:
    metadata:
      labels:
        app: capstone-pj
    spec:
      containers:
        - name: capstone-pj
          image: trunghieuluong/udacity-capstone-project:c01d690
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: capstone-pj
  labels:
    app: capstone-pj
spec:
  type: LoadBalancer
  selector:
    app: capstone-pj
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
